version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - db
      - prisma
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/dbname
    volumes:
      - ./prisma:/app/prisma:rw

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma:rw
      - ./migration.sql:/app/migration.sql:rw
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/dbname
    #   command:
    #     [
    #       "sh",
    #       "./wait-for-db.sh",
    #       "db",
    #       "sh",
    #       "-c",
    #       "npx prisma migrate deploy --preview-feature && sleep infinity",
    # ]
    command: sh -c "npx prisma migrate deploy --preview-feature && sleep infinity"
