version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mysql://username:password@db:3306/dbname
    ports:
      - 8000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://username:password@db:3306/dbname

  prisma-migrate:
    image: node:alpine
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: npx prisma migrate deploy
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/dbname

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
  db-data:
