version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - db
      - prisma

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma
      - ./migration.sql:/app/migration.sql
    environment:
      - DATABASE_URL=mysql://username:password@db:3306/dbname
    command: sh -c "npx prisma migrate dev --preview-feature && sleep infinity"
